pull_secret: ''
ssh_pub_key: ''
ssh_key: |
    <ssh_private_key>

managed_clusters:
# AWS (Amazon) cluster
  - name: cluster-aws
    credentials: aws-creds  # Define the name of credentials that should be used
    platform: aws
    region: us-east-2
    network:
      cluster: 10.128.0.0/14
      machine: 10.0.0.0/16
      service: 172.30.0.0/16
      type: OVNKubernetes
    managed_cluster_version: "4.12"  # Will fetch the last available image of defined version 
# GCP (Google) cluster
  - name: cluster-gcp
    credentials: gcp-creds
    platform: gcp
    region: us-west1
    network:
      cluster: 10.128.0.0/14
      machine: 10.0.0.0/16
      service: 172.30.0.0/16
      type: OpenShiftSDN
    managed_cluster_image: quay.io/openshift-release-dev/ocp-release:4.12.7-multi  # Specific image could be specified
# Azure (Microsoft) cluster
  - name: cluster-azure
    credentials: azure-creds
    platform: azr
    region: centralus
    network:
      cluster: 10.128.0.0/14
      machine: 10.0.0.0/16
      service: 172.30.0.0/16
      type: OVNKubernetes
    managed_cluster_version: "4.11"
# VMware vSphere cluster
  - name: cluster-vmware
    credentials: vmware-creds
    platform: vmw
    network:
      cluster: 10.128.0.0/14
      machine: <Subnet must be aligned to the apiVIP and ingressVIP addresses>
      service: 172.30.0.0/16
      type: OVNKubernetes
    network_name: "<vSphere network name>"
    network_api_vip: "<apiVIP address>"
    network_ingress_vip: "<ingressVIP address>"
    managed_cluster_version: "4.11"

managed_clusters_credentials:
# AWS (Amazon) credentials
  - name: aws-creds
    platform: aws
    namespace: open-cluster-management-hub
    base_domain: <domain name>
    aws_access_key_id: <aws access key id>
    aws_secret_access_key: <aws secret access key>
# GCP (Google) credentials
  - name: gcp-creds
    platform: gcp
    namespace: open-cluster-management-hub
    base_domain: <domain name>
    project_id: <gcp project name>
    os_service_account_json: |
      <service account file content>
# Azure (Microsoft) credentials
  - name: azure-creds
    platform: azr
    namespace: open-cluster-management-hub
    base_domain: <domain name>
    base_domain_resource_group_name: <azure base domain resource group name>
    cloud_name: AzurePublicCloud
    os_service_principal_json: |
      <azure service pricipal file content>
# VMware vSphere credentials
  - name: vmware-creds
    platform: vmw
    namespace: open-cluster-management-hub
    base_domain: <domain name>
    vcenter: <vSphere vCenter url>
    username: <vSphere vCenter username>
    password: <vSphere vCenter password>
    cluster: <vSphere vCenter cluster name>
    datacenter: <vSphere vCenter datacenter name>
    default_datastore: <vSphere vCenter datastore name>
    cacertificate: |
        <vSphere vCenter CA certificate>

# Default cluster resources per platform.
# Could be overriden by definition on the cluster level.
platform_resources:
  aws:
    master_resource:
      type: m5.xlarge
      rootVolume:
        iops: 4000
        size: 100
        type: io1
    worker_resource:
      type: m5.xlarge
      rootVolume:
        iops: 2000
        size: 100
        type: io1
  gcp:
    master_resource:
      type: n1-standard-4
    worker_resource:
      type: n1-standard-4
  azr:
    master_resource:
      type:  Standard_D4s_v3
      osDisk:
        diskSizeGB: 128
    worker_resource:
      type:  Standard_D2s_v3
      osDisk:
        diskSizeGB: 128
      zones:
      - "1"
      - "2"
      - "3"
  vmw:
    master_resource:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
    worker_resource:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
