ocp_image_query_url: https://quay.io/api/v1/repository/openshift-release-dev/ocp-release/tag/
ocp_image_base_url: quay.io/openshift-release-dev/ocp-release

# Architecture of the managed clusters
# Allowed values: x86_64, s390x, ppc64le, aarch64
cluster_architecture: "x86_64"

platform_resources:
  aws:
    master_resource:
      type: m5.xlarge
      rootVolume:
        iops: 4000
        size: 100
        type: io1
    worker_resource:
      type: m5.xlarge
      rootVolume:
        iops: 2000
        size: 100
        type: io1
  gcp:
    master_resource:
      type: n1-standard-4
    worker_resource:
      type: n1-standard-4
  azr:
    master_resource:
      type:  Standard_D4s_v3
      osDisk:
        diskSizeGB: 128
    worker_resource:
      type:  Standard_D2s_v3
      osDisk:
        diskSizeGB: 128
      zones:
      - "1"
      - "2"
      - "3"
  vmw:
    master_resource:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
    worker_resource:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120

