apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "$IMAGE_NAME"
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: "$SOURCE_IMAGE:$IMAGE_TAG"
    generation: 1
    importPolicy: {}
    name: "$IMAGE_TAG"
    referencePolicy:
      type: Source
