apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "$NODE_ROLE"
  name: 99-"$NODE_ROLE"-submariner-registries
spec:
  config:
    ignition:
      version: "$IGNITION_VERSION"
    storage:
      files:
      - contents:
          source: data:text/plain,"$CONFIG_SOURCE"
        filesystem: root
        mode: 0420
        path: /etc/containers/registries.conf.d/submariner-registries.conf
