apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "$ROLE_BINDING_NAME"
  namespace: "$NAMESPACE"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: "$SERVICE_ACCOUNT_NAME"
  namespace: "$NAMESPACE"

