---
- name: Set the version of openshift-install binary to download
  ansible.builtin.set_fact:
    ocp_version: "{%- if item.openshift_version is defined -%}
                  stable-{{ item.openshift_version }}
                  {%- elif openshift_version is not none -%}
                  stable-{{ openshift_version }}
                  {%- else -%}
                  stable
                  {%- endif -%}"

- name: Print selected openshift-install version
  vars:
    msg: |
      Cluster: {{ item.name }}

      Openshift-install binary: {{ ocp_version }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"

- name: Fetch openshift-install client
  ansible.builtin.unarchive:
    src: "{{ openshift_install_url }}/{{ ocp_version }}/{{ openshift_install_binary }}"
    dest: "/tmp/"
    remote_src: yes

- name: "OCP cluster - {{ cluster_state }}"
  vars:
    cluster_state: "{%- if state == 'present' -%}
                    create
                    {%- elif state == 'absent' -%}
                    destroy
                    {%- endif -%}"
  ansible.builtin.command:
    cmd: "/tmp/openshift-install {{ cluster_state }} cluster --dir {{ working_path }}/{{ item.name }}/"
