---
- name: Generate cluster token to authentication
  ansible.builtin.include_role:
    name: cluster_login

- name: Set info state
  ansible.builtin.set_fact:
    info_state: "{%- if state == 'present' -%}
                 Create
                 {%- elif state == 'absent' -%}
                 Destroy
                 {%- endif -%}"

- name: "{{ info_state }} global credentials"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'global-credentials.yaml.j2') | from_yaml }}"
    state: "{{ state }}"
  loop: "{{ managed_clusters_credentials }}"
  no_log: true

- name: "{{ info_state }} Managed Cluster"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'managed-cluster.yaml.j2') | from_yaml }}"
    state: "{{ state }}"
  loop: "{{ managed_clusters }}"

- name: Prepare clusters secrets
  ansible.builtin.include_tasks:
    file: prepare_secrets.yml
  when: state == "present"

- name: "{{ info_state }} cluster MachinePool"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'machine-pool.yaml.j2') | from_yaml }}"
    state: "{{ state }}"
  loop: "{{ managed_clusters }}"

- name: "{{ info_state }} cluster KlusterletAddonConfig"
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'klusterlet-addon-config.yaml.j2') | from_yaml }}"
    state: "{{ state }}"
  loop: "{{ managed_clusters }}"

- name: "{{ info_state }} Cluster Deployment"
  ansible.builtin.include_tasks:
    file: cluster_deployment.yml
  loop: "{{ managed_clusters }}"

- block:
    - name: Wait for cluster provisioning to complete
      kubernetes.core.k8s_info:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: no
        api_version: hive.openshift.io/v1
        kind: ClusterDeployment
        name: "{{ item.name }}"
        namespace: "{{ item.name }}"
        wait: yes
        wait_timeout: 3600
        wait_condition:
          type: Provisioned
          status: True
      loop: "{{ managed_clusters }}"

    - name: Wait for cluster to become ready
      kubernetes.core.k8s_info:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: no
        api_version: hive.openshift.io/v1
        kind: ClusterDeployment
        name: "{{ item.name }}"
        namespace: "{{ item.name }}"
        wait: yes
        wait_timeout: 3600
        wait_condition:
          type: Ready
          status: True
      loop: "{{ managed_clusters }}"
  when: state == "present"

- block:
    - name: Wait for ClusterDeployment removal
      kubernetes.core.k8s_info:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: no
        api_version: hive.openshift.io/v1
        kind: ClusterDeployment
        name: "{{ item.name }}"
        namespace: "{{ item.name }}"
      loop: "{{ managed_clusters }}"
      register: cl_remove
      until: cl_remove.resources | length == 0
      retries: 50
      delay: 15

    - name: Wait for ManagedCluster removal
      kubernetes.core.k8s_info:
        host: "{{ cluster_api }}"
        api_key: "{{ cluster_api_token }}"
        validate_certs: no
        api_version: cluster.open-cluster-management.io/v1
        kind: ManagedCluster
        name: "{{ item.name }}"
        namespace: "{{ item.name }}"
      loop: "{{ managed_clusters }}"
      register: mc_remove
      until: mc_remove.resources | length == 0
      retries: 50
      delay: 15
  when: state == "absent"

- name: Print execution state
  vars:
    msg: |
      {{ info_state }} of Managed Clusters completed
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
