---
- name: Create cluster cloud credentials
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'cloud-secret.yaml.j2') | from_yaml }}"
  loop: "{{ managed_clusters }}"
  no_log: true

- name: Create cluster pull-secret
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'pull-secret.yaml.j2') | from_yaml }}"
  loop: "{{ managed_clusters }}"
  no_log: true

- name: Create cluster private secret key
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'private-key-secret.yaml.j2') | from_yaml }}"
  loop: "{{ managed_clusters }}"
  no_log: true

- name: Create cluster install-config secret
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'install-config-secret.yaml.j2') | from_yaml }}"
  loop: "{{ managed_clusters }}"

- name: Create vSphere CA certificate
  community.okd.k8s:
    host: "{{ cluster_api }}"
    api_key: "{{ cluster_api_token }}"
    validate_certs: no
    definition: "{{ lookup('template', 'vsphere_cert.yml.j2') | from_yaml }}"
  loop: "{{ managed_clusters }}"
  when: item.platform == "vmw"
