apiVersion: v1
kind: Pod
metadata:
  labels:
    label: submariner
spec:
  activeDeadlineSeconds: 18000
  containers:
  - name: jnlp
    image: "image-registry.openshift-image-registry.svc:5000/jenkins-csb-skynet/qe-jenkins-agent:latest"
    workingDir: '/home/jenkins'
    env:
      - name: HOME
        value: '/home/jenkins'
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 256Mi
  - name: submariner
    image: 'quay.io/maxbab/subm-test@sha256:a2428d1e6e1a2f368b02d726a1014e971161f012847fb9c1841edd348ffc417e'
    # imagePullSecrets: 'agent-image-secret'
    ttyEnabled: true
    alwaysPullImage: true
    command: [ 'sleep', '365d' ]
    workingDir: '/home/jenkins'
    env:
      - name: HOME
        value: '/home/jenkins'
      - name: ANSIBLE_COLLECTIONS_PATHS
        value: '/usr/share/ansible/collections'
    resources:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 2000m
        memory: 3Gi
    volumeMounts:
      - name: skynet-data
        mountPath: '/var/skynet-data'
        readOnly: false
  volumes:
    - name: skynet-data
      persistentVolumeClaim:
        claimName: skynet-workspace
