---
cluster_api:
cluster_user: kubeadmin
cluster_pass:

# Specify the version in the format of "2.8", "2.7"
acm_version: "2.8"
snapshot:

acm_namespace: open-cluster-management

registry_secrets:
  - name: "quay.io:443"
    user: <username>
    pass: <password>
  - name: "brew.registry.redhat.io"
    user: <username>
    pass: <password>
